/-
  Constraint Solver

  Solves the constraint graph generated by Gen.lean.
  The solver works in phases:
  1. Solve equality constraints (unification)
  2. Apply substitution to class constraints
  3. Solve class constraints (instance resolution)

  Key improvements over the old Haskell design:
  1. Priority-based solving (var bindings first for efficiency)
  2. Proper instance entailment checking (class name AND type)
  3. Constraint graph for efficient lookup
  4. Continues on errors to report as many as possible
-/

import Soma.Infer.Monad
import Soma.Infer.Unify
import Soma.Infer.Entailment
import Soma.Infer.Gen

namespace Soma.Infer

open Soma.Typing
open Soma.Syntax (Span)
open Soma.Metal (Scope Expr Name)
open InferM (reportError getConstraints getSubst extendSubst getInstanceEnv addConstraint getErrors)
open InstanceEnv (findInstance)

/-! ## Constraint Solving -/

namespace Solver

/-- Solve a single equality constraint, returning the resulting substitution -/
def solveEquality (c : EqualityConstraint) : InferM (Option Subst) := do
  let ctx : UnifyContext := {
    purpose := c.purpose
    expectedSpan := c.lhsSpan
    actualSpan := c.rhsSpan
  }
  match Unify.unifyMono c.lhs c.rhs ctx with
  | .ok σ => return some σ
  | .error err =>
    reportError err
    return none

/-- Solve all equality constraints iteratively -/
partial def solveEqualities : InferM Unit := do
  let mut changed := true
  while changed do
    changed := false
    let graph ← getConstraints
    let sorted := graph.sortedEqualities

    for c in sorted do
      if c.isTrivial then continue

      -- Apply current substitution to the constraint
      let σ ← getSubst
      let c' := c.applySubst σ

      if c'.isTrivial then continue

      -- Try to solve
      match ← solveEquality c' with
      | some σ' =>
        if !σ'.isEmpty then
          extendSubst σ'
          changed := true
      | none => pure ()

    -- Remove trivially satisfied constraints
    modify fun s => { s with constraints := s.constraints.removeTrivial }

/-- Check if a class constraint is satisfied by available instances -/
def solveClassConstraint (c : ClassConstraint) : InferM Bool := do
  let env ← getInstanceEnv
  let state ← get

  -- Try to find an instance
  match findInstance env c.toConstraint state.freshCounter with
  | some (_inst, σ, subConstraints, newFreshCounter) =>
    -- Update fresh counter
    modify fun s => { s with freshCounter := newFreshCounter }
    -- Extend substitution
    extendSubst σ
    -- Add sub-constraints from the instance context
    for subC in subConstraints do
      addConstraint subC c.span
    return true
  | none =>
    -- No instance found - this may be deferred or an error
    return false

/-- Solve class constraints -/
def solveClassConstraints : InferM Unit := do
  let mut changed := true
  let mut iterations := 0
  let maxIterations := 100  -- Prevent infinite loops

  while changed && iterations < maxIterations do
    changed := false
    iterations := iterations + 1

    -- Apply current substitution to all class constraints
    let σ ← getSubst
    modify fun s => { s with constraints := s.constraints.applySubst σ }

    let graph ← getConstraints
    let mut remaining := #[]

    for c in graph.classes do
      -- Check if we can solve this constraint
      if ← solveClassConstraint c then
        changed := true
      else
        remaining := remaining.push c

    -- Update constraints to only the remaining ones
    modify fun s => { s with
      constraints := { s.constraints with classes := remaining }
    }

/-- Report errors for unsolved class constraints -/
def reportUnsolvedConstraints : InferM Unit := do
  let graph ← getConstraints

  for c in graph.classes do
    reportError (.noInstance c.toConstraint c.span)

/-- Check for ambiguous type variables -/
def checkAmbiguousTypes (_originalExprSpan : Span) : InferM Unit := do
  let σ ← getSubst

  -- Find all type variables in the substitution that map to other variables
  for (varId, ty) in σ.toList do
    match ty with
    | .var v =>
      -- Check if this variable is used in any constraint
      let graph ← getConstraints
      let hasConstraint := graph.classes.any fun c =>
        c.freeVars.contains varId || c.freeVars.contains v.id
      if !hasConstraint then
        -- Completely unconstrained variable - may be ambiguous
        -- Only report if it appears in constraints but can't be resolved
        pure ()
    | _ => pure ()

/-- Main solving entry point -/
def solve (exprSpan : Span) : InferM Unit := do
  -- Phase 1: Solve equality constraints
  solveEqualities

  -- Phase 2: Solve class constraints
  solveClassConstraints

  -- Phase 3: Report any unsolved constraints
  reportUnsolvedConstraints

  -- Phase 4: Check for ambiguous types
  checkAmbiguousTypes exprSpan

end Solver

/-- Result of type inference -/
structure InferResult where
  /-- The inferred type -/
  ty : MonoTy
  /-- The final substitution -/
  subst : Subst
  /-- Any errors encountered -/
  errors : Array InferError
  /-- Remaining unsolved constraints (for qualified types) -/
  constraints : Array Typing.Constraint

instance : Inhabited InferResult := ⟨{
  ty := .starPrim .unit
  subst := Subst.empty
  errors := #[]
  constraints := #[]
}⟩

namespace InferResult

/-- Check if inference succeeded (no errors) -/
def isSuccess (r : InferResult) : Bool := r.errors.isEmpty

/-- Get the fully substituted type -/
def finalType (r : InferResult) : MonoTy := r.subst.apply r.ty

end InferResult

/-- Infer the type of an expression -/
def inferExpr {scope : Scope} (expr : Metal.Expr Unit scope)
    (ctx : InferContext) : InferResult :=
  let m : InferM InferResult := do
    -- Generate constraints
    let ty ← Gen.genExpr expr

    -- Solve constraints
    Solver.solve expr.span

    -- Get final state
    let σ ← getSubst
    let errors ← getErrors
    let graph ← getConstraints

    -- Collect remaining class constraints
    let constraints := graph.classes.map (·.toConstraint)

    return { ty, subst := σ, errors, constraints }

  (m.run ctx).1

/-- Infer and generalize the type of an expression -/
def inferAndGeneralize {scope : Scope} (expr : Metal.Expr Unit scope)
    (ctx : InferContext) : QualifiedType × Array InferError :=
  let result := inferExpr expr ctx
  if result.isSuccess then
    let finalTy := result.finalType
    -- Generalize over free variables
    let tyVars := finalTy.freeVarsUnique
    let qt : QualifiedType := {
      vars := tyVars
      constraints := result.constraints
      body := finalTy
    }
    (qt, #[])
  else
    -- Return a dummy type with errors
    let qt : QualifiedType := {
      vars := #[]
      constraints := #[]
      body := result.ty
    }
    (qt, result.errors)

/-- Infer types for a module (collection of functions) -/
structure ModuleInferResult where
  /-- Inferred types for each function -/
  types : Std.HashMap String QualifiedType
  /-- All errors -/
  errors : Array InferError
  deriving Inhabited

/-- Build the initial type environment from function signatures -/
def buildInitialEnv (signatures : Array (String × QualifiedType × Metal.Name))
    : TypeEnv :=
  signatures.foldl (init := TypeEnv.empty) fun env (name, qt, metalName) =>
    env.addFunction name { qualType := qt, metalName := metalName }

/-- Build instance environment from instance declarations -/
def buildInstanceEnv (instances : Array InstanceDecl) : InstanceEnv :=
  instances.foldl (init := InstanceEnv.empty) fun env inst =>
    env.addInstance inst

end Soma.Infer
