/-
  Constraint Solver

  Solves the constraint graph generated by Gen.lean.
  The solver works in phases:
  1. Solve equality constraints (unification)
  2. Apply substitution to class constraints
  3. Solve class constraints (instance resolution)

  Key improvements over the old Haskell design:
  1. Priority-based solving (var bindings first for efficiency)
  2. Proper instance entailment checking (class name AND type)
  3. Constraint graph for efficient lookup
  4. Continues on errors to report as many as possible
-/

import Soma.Infer.Monad
import Soma.Infer.Unify
import Soma.Infer.Entailment
import Soma.Infer.Gen

namespace Soma.Infer

open Soma.Typing
open Soma.Syntax (Span)
open Soma.Metal (Scope Expr Name)
open InferM (reportError getConstraints getSubst extendSubst getInstanceEnv addConstraint getErrors)
open InstanceEnv (findInstance)

/-! ## Constraint Solving -/

namespace Solver

/-- Solve a single equality constraint, returning the resulting substitution -/
def solveEquality (c : EqualityConstraint) : InferM (Option Subst) := do
  let ctx : UnifyContext := {
    purpose := c.purpose
    expectedSpan := c.rhsSpan
    actualSpan := c.lhsSpan
  }
  match Unify.unifyMono c.lhs c.rhs ctx with
  | .ok σ => return some σ
  | .error err =>
    reportError err
    return none

/-- Solve all equality constraints iteratively -/
partial def solveEqualities : InferM Unit := do
  -- Track constraint IDs that have failed to avoid duplicate error reporting
  let mut failedIds : Std.HashSet Nat := {}
  let mut changed := true
  while changed do
    changed := false
    let graph ← getConstraints
    let sorted := graph.sortedEqualities

    for c in sorted do
      -- Skip constraints that have already failed
      if failedIds.contains c.id then continue
      if c.isTrivial then continue

      -- Apply current substitution to the constraint
      let σ ← getSubst
      let c' := c.applySubst σ

      if c'.isTrivial then continue

      -- Try to solve
      match ← solveEquality c' with
      | some σ' =>
        if !σ'.isEmpty then
          extendSubst σ'
          changed := true
      | none =>
        -- Mark this constraint as failed so we don't report the error again
        failedIds := failedIds.insert c.id

    -- Remove trivially satisfied constraints
    modify fun s => { s with constraints := s.constraints.removeTrivial }

/-- Check if a class constraint is satisfied by available instances -/
def solveClassConstraint (c : ClassConstraint) : InferM Bool := do
  let env ← getInstanceEnv
  let state ← get

  -- Try to find an instance
  match findInstance env c.toConstraint state.freshCounter with
  | some (_inst, σ, subConstraints, newFreshCounter) =>
    -- Update fresh counter
    modify fun s => { s with freshCounter := newFreshCounter }
    -- Extend substitution
    extendSubst σ
    -- Add sub-constraints from the instance context
    for subC in subConstraints do
      addConstraint subC c.span
    return true
  | none =>
    -- No instance found - this may be deferred or an error
    return false

/-- Solve class constraints -/
def solveClassConstraints : InferM Unit := do
  let mut changed := true
  let mut iterations := 0
  let maxIterations := 100  -- Prevent infinite loops

  while changed && iterations < maxIterations do
    changed := false
    iterations := iterations + 1

    -- Apply current substitution to all class constraints
    let σ ← getSubst
    modify fun s => { s with constraints := s.constraints.applySubst σ }

    let graph ← getConstraints
    let mut remaining := #[]

    for c in graph.classes do
      -- Check if we can solve this constraint
      if ← solveClassConstraint c then
        changed := true
      else
        remaining := remaining.push c

    -- Update constraints to only the remaining ones
    modify fun s => { s with
      constraints := { s.constraints with classes := remaining }
    }

/-- Report errors for unsolved class constraints -/
def reportUnsolvedConstraints : InferM Unit := do
  let graph ← getConstraints

  for c in graph.classes do
    reportError (.noInstance c.toConstraint c.span)

/-- Check for ambiguous type variables in unsolved class constraints.
    A type variable is ambiguous if:
    1. It appears in an unsolved class constraint
    2. It does not appear in the final inferred type
    This means the variable cannot be determined from the context. -/
def checkAmbiguousTypes (exprSpan : Span) (inferredType : MonoTy) : InferM Unit := do
  let σ ← getSubst
  let graph ← getConstraints

  -- Get all type variables in the final inferred type (after substitution)
  let finalTy := σ.apply inferredType
  let tyVars : Std.HashSet Nat := finalTy.freeVars.foldl (init := {}) fun acc v => acc.insert v.id

  -- Check each unsolved class constraint for ambiguous variables
  for c in graph.classes do
    -- Get all type variables in this constraint
    let constraintVars := c.freeVars
    -- Find variables that are in the constraint but not in the type
    for varId in constraintVars do
      if !tyVars.contains varId then
        let varInfo := c.args.findSome? fun arg =>
          arg.freeVars.find? fun v => v.id == varId
        match varInfo with
        | some v => reportError (.ambiguousType v exprSpan)
        | none => pure ()

/-- Main solving entry point -/
def solve (exprSpan : Span) (inferredType : MonoTy) : InferM Unit := do
  -- Phase 1: Solve equality constraints
  solveEqualities

  -- Phase 2: Solve class constraints
  solveClassConstraints

  -- Phase 3: Report any unsolved constraints
  reportUnsolvedConstraints

  -- Phase 4: Check for ambiguous types
  checkAmbiguousTypes exprSpan inferredType

end Solver

/-- Result of type inference -/
structure InferResult where
  /-- The inferred type -/
  ty : MonoTy
  /-- The final substitution -/
  subst : Subst
  /-- Any errors encountered -/
  errors : Array InferError
  /-- Remaining unsolved constraints (for qualified types) -/
  constraints : Array Typing.Constraint

instance : Inhabited InferResult := ⟨{
  ty := .starPrim .unit
  subst := Subst.empty
  errors := #[]
  constraints := #[]
}⟩

namespace InferResult

/-- Check if inference succeeded (no errors) -/
def isSuccess (r : InferResult) : Bool := r.errors.isEmpty

/-- Get the fully substituted type -/
def finalType (r : InferResult) : MonoTy := r.subst.apply r.ty

end InferResult

/-- Infer the type of an expression -/
def inferExpr {scope : Scope} (expr : Metal.Expr Unit scope)
    (ctx : InferContext) : InferResult :=
  let m : InferM InferResult := do
    -- Generate constraints (now returns type and typed expression)
    let (ty, _typedExpr) ← Gen.genExpr expr

    -- Solve constraints (pass inferred type for ambiguity checking)
    Solver.solve expr.span ty

    -- Get final state
    let σ ← getSubst
    let errors ← getErrors
    let graph ← getConstraints

    -- Collect remaining class constraints
    let constraints := graph.classes.map (·.toConstraint)

    return { ty, subst := σ, errors, constraints }

  (m.run ctx).1

/-- Infer and generalize the type of an expression -/
def inferAndGeneralize {scope : Scope} (expr : Metal.Expr Unit scope)
    (ctx : InferContext) : QualifiedType × Array InferError :=
  let result := inferExpr expr ctx
  if result.isSuccess then
    let finalTy := result.finalType
    -- Generalize over free variables
    let tyVars := finalTy.freeVarsUnique
    let qt : QualifiedType := {
      vars := tyVars
      constraints := result.constraints
      body := finalTy
    }
    (qt, #[])
  else
    -- Return a dummy type with errors
    let qt : QualifiedType := {
      vars := #[]
      constraints := #[]
      body := result.ty
    }
    (qt, result.errors)

/-- Infer types for a module (collection of functions) -/
structure ModuleInferResult where
  /-- Inferred types for each function -/
  types : Std.HashMap String QualifiedType
  /-- All errors -/
  errors : Array InferError
  deriving Inhabited

/-- Build the initial type environment from function signatures -/
def buildInitialEnv (signatures : Array (String × QualifiedType × Metal.Name))
    : TypeEnv :=
  signatures.foldl (init := TypeEnv.empty) fun env (name, qt, metalName) =>
    env.addFunction name { qualType := qt, metalName := metalName }

/-- Build instance environment from instance declarations -/
def buildInstanceEnv (instances : Array InstanceDecl) : InstanceEnv :=
  instances.foldl (init := InstanceEnv.empty) fun env inst =>
    env.addInstance inst

end Soma.Infer
