cabal-version: 3.12
name: soma
version: 0.1.0.0
license: MIT
license-file: LICENSE
author: Gabriel
maintainer: gabriel@minatel.dev
category: Programming Language
build-type: Simple
extra-doc-files: CHANGELOG.md

common warnings
  ghc-options:
    -Wall
    -fprof-auto
    -rtsopts

library
  import: warnings
  exposed-modules:
    Format.Errors
    Format.Trees
    Inference.Assembler
    Inference.Core
    Inference.Errors
    Inference.Gen
    Inference.Naming
    Inference.Resolver
    Inference.Solving
    Inference.Substitution
    Inference.Tree
    Lexing.Errors
    Lexing.Lexer
    Lexing.Position
    Parsing.Ast
    Parsing.Atoms
    Parsing.Bindings
    Parsing.DataTypes
    Parsing.Errors
    Parsing.Imports
    Parsing.Intrinsics
    Parsing.Parser
    Parsing.Patterns
    Parsing.Traits
    Parsing.Types
    Project.Extracts
    Project.Graph
    Project.Module
    Project.Parsing
    Project.Symbols
    Syntax.Ops
    Syntax.Patterns
    Syntax.Tree
    Typing.Currying
    Typing.Types
    Utils.Lists

  hs-source-dirs: compiler/lib
  build-depends:
    async >=2.2.5,
    base >=4.19.2.0,
    bytestring >=0.12.0.0,
    containers >=0.6,
    directory >=1.3.8.3,
    filepath >=1.5.2.0,
    megaparsec >=9.7,
    mtl >=2.2,
    text >=2.1,

  default-language: Haskell2010

executable compiler
  import: warnings
  main-is: Main.hs
  hs-source-dirs: compiler/exe
  build-depends:
    aeson >=2.2.3.0,
    ansi-terminal >=1.0,
    async,
    base,
    binary >=0.8,
    bytestring,
    containers,
    cryptohash-sha256 >=0.11,
    directory,
    filepath,
    hashable,
    mtl,
    optparse-applicative >=0.19.0.0,
    process,
    soma,
    tar >=0.7.0.0,
    text,
    zlib >=0.7.0.0,

  other-modules:
    Alloy.Build
    Alloy.CSE
    Alloy.Decisions
    Alloy.Defunc
    Alloy.ExpandIntrinsics
    Alloy.HoistAllocas
    Alloy.Ir
    Alloy.Lower
    Alloy.MonadicInline
    Alloy.Monomorphize
    Alloy.Naming
    Alloy.PromoteRefs
    Alloy.ReaderRewrite
    Alloy.Simplify
    Alloy.Subst
    Alloy.Uniqueness
    Build.Incremental
    Build.Metadata
    Build.Tarball
    Config.Options
    Llvm.Dependencies
    Llvm.Gen.Core
    Llvm.Gen.Dictionary
    Llvm.Gen.Entry
    Llvm.Gen.Function
    Llvm.Gen.Instr
    Llvm.Gen.Intrinsics
    Llvm.Gen.Op
    Llvm.Gen.OperandPass
    Llvm.Gen.Operands
    Llvm.Gen.Templates
    Llvm.Gen.TypeConversion
    Llvm.Instructions
    Llvm.Ir
    Llvm.Modules
    Llvm.Types
    Llvm.Values
    Logging.Errors
    Logging.Trees
    Metal.Expr
    Metal.Function
    Metal.Gen.Binding
    Metal.Gen.Core
    Metal.Gen.DataTypes
    Metal.Gen.Entry
    Metal.Gen.Extracts
    Metal.Gen.Metadata
    Metal.Gen.Value
    Metal.Lift
    Metal.Metadata
    Metal.Module
    Metal.MonadNormalize
    Metal.MonadProfile
    Orphans.Binary

  default-language: Haskell2010
