cabal-version:      3.12
name:               soma
version:            0.1.0.0
-- synopsis:
-- description:
license:            MIT
license-file:       LICENSE
author:             Gabriel
maintainer:         gabriel@minatel.dev
-- copyright:
category:           Programming Language
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options:       -Wall -fprof-auto -rtsopts

library
  import:           warnings
  exposed-modules:  Typing.Types
                    Syntax.Patterns
                    Syntax.Tree
                    Syntax.Ops
                    Project.Name
                    Inference.Errors
                    Inference.Resolver
                    Inference.Core
                    Inference.Gen
                    Inference.Solving
                    Inference.Tree
                    Inference.Assembler
                    Lexing.Lexer
                    Lexing.Errors
                    Lexing.Position
                    Parsing.Errors
                    Parsing.Parser
                    Parsing.Ast
                    Parsing.Bindings
                    Parsing.Types
                    Parsing.Patterns
                    Parsing.Atoms
                    Logging.ErrorPrinter
                    Logging.PrettyTrees
                    Logging.Errors
                    Project.Module
                    Project.Graph
                    Project.Parsing
                    Project.Processing
                    Utils.Lists
                    Config.Options
                    Typing.Currying
  hs-source-dirs:   app
  build-depends:    base >= 4.19.2.0,
                    ansi-terminal >= 1.0,
                    containers >= 0.6,
                    mtl >= 2.2,
                    directory >= 1.3.8.3,
                    filepath >= 1.5.2.0,
                    async >= 2.2.5
  default-language: Haskell2010

executable soma
  import:           warnings
  main-is:          Main.hs
  hs-source-dirs:   app
  build-depends:    base,
                    soma,
                    ansi-terminal,
                    containers,
                    mtl,
                    directory,
                    filepath,
                    async
  default-language: Haskell2010


test-suite spec-tests
  type:             exitcode-stdio-1.0
  hs-source-dirs:   test
  main-is:          SpecMain.hs
  build-depends:    base >=4.19.2.0 && <5,
                    HUnit,
                    hspec,
                    containers,
                    mtl,
                    transformers,
                    soma
  other-modules:
  default-language: Haskell2010