cabal-version:      3.12
name:               soma
version:            0.1.0.0
-- synopsis:
-- description:
license:            MIT
license-file:       LICENSE
author:             Gabriel
maintainer:         gabriel@minatel.dev
-- copyright:
category:           Programming Language
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options: -Wall

executable soma
    import:           warnings
    main-is:          Main.hs
    other-modules:    Lexing.Lexer
                      Lexing.Errors
                      Parsing.Parser
                      Parsing.Errors
                      Parsing.Tree
                      Parsing.Type
                      Parsing.Ops
                      Parsing.Pattern
                      Analysis.Inference
                      Analysis.Tree
                      Analysis.Errors
                      Logging.ErrorPrinter

    build-depends:    base >= 4.19.2.0,
                      ansi-terminal >= 1.0,
                      containers >= 0.6,
                      mtl >= 2.2,
    hs-source-dirs:   app
    default-language: Haskell2010
