name = "soma"
version = "0.1.0"
defaultTargets = ["somac"]
testDriver = "test"

[[require]]
scope = "leanprover"
name = "Cli"

[[require]]
name = "kenosis"
git = "https://github.com/SrGaabriel/kenosis"
rev = "main"

[[lean_lib]]
name = "Soma"
srcDir = "Lib"

[[lean_lib]]
name = "Somac"
srcDir = "Exe"
globs = ["Somac.+"]

[[lean_exe]]
name = "somac"
root = "Somac"
srcDir = "Exe"

[[lean_lib]]
name = "Test"

[[lean_exe]]
name = "test"
root = "Test.Main"
