name = "soma"
version = "0.1.0"
defaultTargets = ["somac"]
testDriver = "test"

[[require]]
scope = "leanprover"
name = "Cli"

[[lean_lib]]
name = "Soma"

[[lean_exe]]
name = "somac"
root = "Soma.Main"

[[lean_exe]]
name = "test"
root = "test.Main"
